### ISSUE TITLE
Unread messages indicator bug

### ISSUE THREAD

**Issue by Nekomajin42** [RunninglVlan/Facebook-Status#11]
Hello!

I am using this extension in Vivaldi with a local installation. I have downloaded the master branch from here.

A few month ago a strange bug appeared. The unread messages counter gets stuck, if I am the last person to reply in a conversation. So:

* Friend requests and notifications work fine
* If I get a new message and read it, the counter resets to 0
* If I send a new message to anyone, the counter sticks at 1, until I manually mark the conversation as read

Any idea?

**Comment by RunninglVlan** [comment]
Hi, I'm using latest Opera, and messages started to not show at some point - mobile site doesn't have their count on first load. =D Because of that I started using Opera's Messenger on the sidebar (still using this extension for Friend requests and Notifications though). Although I could have added option to not use mobile site to check FB statuses. =D But as I'm a bit lazy, I chose the easy way.
So I don't know about your problem. It seems that it could be just related to FB changing their algorithms again. =D I mean it seems it's not directly related to extension's code, but you can debug and confirm it. ;)

**Comment by Nekomajin42** [comment]
I think this issue is related to the server side algorithm, too. But I keep the Messenger in a pinned tab all the time, and I can't see the issue there, on the tab notification.

**Comment by RunninglVlan** [comment]
Check https://m.facebook.com/, this is the first site extension uses to get all statuses - lightweight mobile site. If you won't find any problems there, then try debugging extension code and adding breakpoint to `Parser#parseMobile`. What you see in your tab might differ from what extension sees, as it gets only first version of the document which FB server returns it, not the document version which is updated asynchronously (which we see).

**Comment by Nekomajin42** [comment]
I'm tinkering with my own implementation, and I've encountered with the same issue, so the problem has to be on the other end. I will let you know, if I find a solution.

**Comment by Nekomajin42** [comment]
It seems that the guys at Facebook fixed this issue a few days ago.
